name: macOS Runner
# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  test:
    # The type of runner that the job will run on
    # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-13
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
